# Generated by Django 5.0.6 on 2024-06-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_tag_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='title',
            field=models.CharField(default=False, max_length=256, verbose_name='Scope'),
        ),
    ]
