# Generated by Django 5.0.6 on 2024-06-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_scope_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='title',
            field=models.CharField(default='не знаю, зачем это поле от меня требовал джанго...', max_length=256, verbose_name='Scope_title'),
        ),
    ]
