# Generated by Django 5.0.6 on 2024-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_title_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='tag', through='articles.Scope', to='articles.article'),
        ),
    ]
